#

# NORMALIZATION

## Normalization is one of the most basic preprocessing techniques in
data analytics. This involves centering and scaling process. Centering means subtracting the data from the
mean and scaling means dividing with its standard deviation. Mathematically, normalization can be
expressed as: 𝑍 = ( 𝑋 − 𝑥̅ ) / 𝜎
In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and
.std() calls.
In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
ndarray as X_normalized.npy

In [12]:
# Import necessary library
import numpy as np

#  Create a random 5x5 ndarray and store it in variable X
X = np.random.rand(5, 5)  # Creates a 5x5 array with random values between 0 and 1

# Step 2: Calculate the mean and standard deviation of the array
mean = X.mean()
std_dev = X.std()

# Step 3: Normalize X using the Z-score formula
X_normalized = (X - mean) / std_dev

# Step 4: Save the normalized array as X_normalized.npy
np.save('X_normalized.npy', X_normalized)

# Display the original and normalized arrays
print("Original Array:\n", X)
print("\nNormalized Array:\n", X_normalized)

Original Array:
 [[0.40220167 0.85573241 0.67769953 0.07595489 0.90257046]
 [0.55421268 0.59890021 0.57799974 0.07342465 0.27420871]
 [0.62673556 0.70468794 0.34210057 0.19660481 0.27378914]
 [0.7843327  0.56418443 0.41737069 0.40393942 0.14171333]
 [0.03218023 0.83913044 0.10025101 0.02429612 0.48927271]]

Normalized Array:
 [[-0.12956533  1.54274695  0.88628304 -1.33254112  1.71545378]
 [ 0.43094767  0.59572485  0.51865816 -1.34187093 -0.60151615]
 [ 0.69836264  0.98579788 -0.35117725 -0.88766646 -0.60306323]
 [ 1.27947347  0.46771669 -0.07363232 -0.12315771 -1.09006884]
 [-1.49395224  1.48153019 -1.24295359 -1.52302347  0.19149333]]


In [13]:
#Loads the 'X_normalized.npy' file for verification purposes
np.load('X_normalized.npy')

array([[-0.12956533,  1.54274695,  0.88628304, -1.33254112,  1.71545378],
       [ 0.43094767,  0.59572485,  0.51865816, -1.34187093, -0.60151615],
       [ 0.69836264,  0.98579788, -0.35117725, -0.88766646, -0.60306323],
       [ 1.27947347,  0.46771669, -0.07363232, -0.12315771, -1.09006884],
       [-1.49395224,  1.48153019, -1.24295359, -1.52302347,  0.19149333]])

## DIVISIBLE BY 3 PROBLEM: Create the following 10 x 10 ndarray.
which are the squares of the first 100 positive integers.
From this ndarray, determine all the elements that are divisible by 32X


In [5]:
# Import necessary library
import numpy as np

# Step 1: Create an array of the first 100 positive integers and square them
numbers = np.arange(1, 101)  # Array of integers from 1 to 100
squares = numbers ** 2       # Square each element

# Step 2: Reshape the array into a 10x10 ndarray
A = squares.reshape(10, 10)

# Step 3: Find all elements in the array that are divisible by 3
divisible_by_3 = A[A % 3 == 0]

# Step 4: Save the result as div_by_3.npy
np.save('div_by_3.npy', divisible_by_3)

# Display the original array and elements divisible by 3
print("10x10 Array of Squares:\n", A)
print("\nElements Divisible by 3:\n", divisible_by_3)

10x10 Array of Squares:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Elements Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [9]:
#loads the div by 3.npy to verify the answers
np.load('div_by_3.npy')

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])